### ISSUE TITLE
PermissionError

### ISSUE THREAD

**Issue by harukaxxxx** [alexandersokol/sd-model-organizer#31] opened 2023-06-20 23:38 UTC
When downloading model, somtime can't download preview image
```
Traceback (most recent call last):
  File "D:\ProgramFiles\StableDiffusion\stable-diffusion-webui\extensions\sd-model-organizer\scripts\mo\dl\download_manager.py", line 285, in _download_record
    for upd in preview_downloader.download(record.preview_url, temp.name, preview_filename,
  File "D:\ProgramFiles\StableDiffusion\stable-diffusion-webui\extensions\sd-model-organizer\scripts\mo\dl\http_downloader.py", line 43, in download
    with open(destination_file, 'wb') as file:
PermissionError: [Errno 13] Permission denied: 'C:\\Users\\haruk\\AppData\\Local\\Temp\\tmpmhog_enp'
GoodHands-beta2.jpg: 0.00iB [00:00, ?iB/s]
```

**Comment by alexandersokol** [comment] 2023-06-21 17:13
Hello, the issue is fixed in main branch.

**Closed by alexandersokol** 2023-06-21 17:13 UTC
